name: "Release"

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
  
    - name: Export
      uses: firebelley/godot-export@v5.2.1
      id: export
      with:
        godot_executable_download_url: https://github.com/godotengine/godot-builds/releases/download/4.3-dev6/Godot_v4.3-dev6_mono_linux_x86_64.zip
        godot_export_templates_download_url: https://github.com/godotengine/godot-builds/releases/download/4.3-dev6/Godot_v4.3-dev6_mono_export_templates.tpz
        relative_project_path: ./src/
        archive_output: true

    - name: Release
      uses: svenstaro/upload-release-action@v2
      with:
        tag: ${{ github.ref }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ steps.export.outputs.archive_directory }}/*
        file_glob: true
        overwrite: true